// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads all projects from disk.
 */
async loadProjects() : Promise<Result<Project[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves all projects to disk.
 */
async saveProjects(projects: Project[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_projects", { projects }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads all environments from disk.
 */
async loadEnvironments() : Promise<Result<Environment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_environments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves all environments to disk.
 */
async saveEnvironments(environments: Environment[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_environments", { environments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads all integrations from disk.
 */
async loadIntegrations() : Promise<Result<Integration[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_integrations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves all integrations to disk.
 */
async saveIntegrations(integrations: Integration[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_integrations", { integrations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads all mappings from disk.
 */
async loadMappings() : Promise<Result<Mapping[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_mappings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves all mappings to disk.
 */
async saveMappings(mappings: Mapping[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_mappings", { mappings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves integration credentials to the OS keyring.
 */
async saveIntegrationCredentials(integrationId: string, credentials: IntegrationCredentials) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_integration_credentials", { integrationId, credentials }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets integration credentials from the OS keyring.
 */
async getIntegrationCredentials(integrationId: string) : Promise<Result<IntegrationCredentials | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_integration_credentials", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes integration credentials from the OS keyring.
 */
async deleteIntegrationCredentials(integrationId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_integration_credentials", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches GitLab projects for a given integration.
 */
async fetchGitlabProjects(integrationId: string) : Promise<Result<GitLabProject[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_gitlab_projects", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches GitLab pipelines for a given project.
 */
async fetchGitlabPipelines(integrationId: string, projectId: number) : Promise<Result<GitLabPipeline[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_gitlab_pipelines", { integrationId, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches GitLab webhooks for a given project.
 */
async fetchGitlabWebhooks(integrationId: string, projectId: number) : Promise<Result<GitLabWebhook[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_gitlab_webhooks", { integrationId, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Triggers a GitLab pipeline for a given project.
 */
async triggerGitlabPipeline(integrationId: string, projectId: number, ref: string) : Promise<Result<GitLabPipeline, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_gitlab_pipeline", { integrationId, projectId, ref }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches Jenkins jobs for a given integration.
 */
async fetchJenkinsJobs(integrationId: string) : Promise<Result<JenkinsJob[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_jenkins_jobs", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches Jenkins builds for a given job.
 */
async fetchJenkinsBuilds(integrationId: string, jobName: string) : Promise<Result<JenkinsBuild[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_jenkins_builds", { integrationId, jobName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches detailed information for a specific Jenkins build.
 */
async fetchJenkinsBuildDetails(integrationId: string, jobName: string, buildNumber: number) : Promise<Result<JenkinsBuild, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_jenkins_build_details", { integrationId, jobName, buildNumber }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Triggers a Jenkins build for a given job.
 */
async triggerJenkinsBuild(integrationId: string, jobName: string, parameters: Partial<{ [key in string]: string }> | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_jenkins_build", { integrationId, jobName, parameters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches Kubernetes namespaces for a given integration.
 */
async fetchK8sNamespaces(integrationId: string) : Promise<Result<K8sNamespace[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_k8s_namespaces", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches Kubernetes pods in a specific namespace.
 */
async fetchK8sPods(integrationId: string, namespace: string) : Promise<Result<K8sPod[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_k8s_pods", { integrationId, namespace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches Kubernetes services in a specific namespace.
 */
async fetchK8sServices(integrationId: string, namespace: string) : Promise<Result<K8sService[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_k8s_services", { integrationId, namespace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches detailed information for a specific Kubernetes pod.
 */
async fetchK8sPodDetails(integrationId: string, namespace: string, podName: string) : Promise<Result<K8sPod, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_k8s_pod_details", { integrationId, namespace, podName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches SonarQube projects for a given integration.
 */
async fetchSonarqubeProjects(integrationId: string) : Promise<Result<SonarQubeProject[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_sonarqube_projects", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches SonarQube metrics for a given project.
 */
async fetchSonarqubeMetrics(integrationId: string, projectKey: string) : Promise<Result<SonarQubeMetrics, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_sonarqube_metrics", { integrationId, projectKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches Keycloak realms for a given integration.
 */
async fetchKeycloakRealms(integrationId: string) : Promise<Result<KeycloakRealm[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_keycloak_realms", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches Keycloak clients for a given realm.
 */
async fetchKeycloakClients(integrationId: string, realm: string) : Promise<Result<KeycloakClient[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_keycloak_clients", { integrationId, realm }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
/**
 * An environment represents a deployment target (dev, staging, prod, etc.)
 */
export type Environment = { 
/**
 * Unique identifier for the environment
 */
id: string; 
/**
 * Environment name (e.g., "dev", "staging", "prod")
 */
name: string; 
/**
 * Kubernetes namespace (if applicable)
 */
namespace: string | null; 
/**
 * ID of the project this environment belongs to
 */
project_id: string }
/**
 * GitLab pipeline representation.
 */
export type GitLabPipeline = { 
/**
 * Pipeline ID
 */
id: number; 
/**
 * Pipeline status (e.g., "success", "failed", "running", "pending")
 */
status: string; 
/**
 * Git reference (branch or tag)
 */
ref: string; 
/**
 * Creation timestamp (ISO 8601 format)
 */
created_at: string }
/**
 * GitLab project representation.
 */
export type GitLabProject = { 
/**
 * Project ID
 */
id: number; 
/**
 * Project name
 */
name: string; 
/**
 * Project path (e.g., "group/project")
 */
path: string; 
/**
 * Web URL to access the project
 */
web_url: string }
/**
 * GitLab webhook representation.
 */
export type GitLabWebhook = { 
/**
 * Webhook ID
 */
id: number; 
/**
 * Webhook URL
 */
url: string; 
/**
 * List of events this webhook subscribes to
 */
events: string[] }
/**
 * Integration configuration (does not contain credentials)
 */
export type Integration = { 
/**
 * Unique identifier for the integration
 */
id: string; 
/**
 * Type of integration
 */
type: IntegrationType; 
/**
 * Human-readable integration name
 */
name: string; 
/**
 * Base URL of the integration service
 */
base_url: string; 
/**
 * Reference to credentials stored in OS keyring
 * This is the key used to retrieve credentials from keyring
 */
credentials_ref: string | null }
/**
 * Credentials for an integration (stored securely in OS keyring)
 */
export type IntegrationCredentials = { 
/**
 * API token or access token
 */
token: string | null; 
/**
 * Username (if applicable)
 */
username: string | null; 
/**
 * Password (if applicable)
 */
password: string | null; 
/**
 * Additional custom fields as key-value pairs
 */
custom?: Partial<{ [key in string]: string }> }
/**
 * Type of integration system
 */
export type IntegrationType = "gitlab" | "jenkins" | "kubernetes" | "sonarqube" | "keycloak"
/**
 * Jenkins build representation.
 */
export type JenkinsBuild = { 
/**
 * Build number
 */
number: number; 
/**
 * Build status
 */
status: JenkinsBuildStatus; 
/**
 * Build timestamp (Unix timestamp in milliseconds, as string to avoid i64 BigInt issues)
 */
timestamp: string; 
/**
 * Build URL
 */
url: string; 
/**
 * Build duration in milliseconds (None if still building, as string to avoid i64 BigInt issues)
 */
duration: string | null }
/**
 * Jenkins build status enumeration.
 */
export type JenkinsBuildStatus = "success" | "failure" | "unstable" | "aborted" | "notbuilt" | "building" | "pending"
/**
 * Jenkins job representation.
 */
export type JenkinsJob = { 
/**
 * Job name
 */
name: string; 
/**
 * Job URL
 */
url: string; 
/**
 * Job color/status indicator (e.g., "blue" for success, "red" for failure, "notbuilt" for not built)
 */
color: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Kubernetes namespace representation.
 */
export type K8sNamespace = { 
/**
 * Namespace name
 */
name: string; 
/**
 * Namespace status (e.g., "Active", "Terminating")
 */
status: string; 
/**
 * Creation timestamp (ISO 8601 format)
 */
created_at: string }
/**
 * Kubernetes pod representation.
 */
export type K8sPod = { 
/**
 * Pod name
 */
name: string; 
/**
 * Namespace the pod belongs to
 */
namespace: string; 
/**
 * Pod status (e.g., "Running", "Pending", "Failed", "Succeeded")
 */
status: string; 
/**
 * List of container names in the pod
 */
containers: string[]; 
/**
 * Node name where the pod is running
 */
node: string | null }
/**
 * Kubernetes service representation.
 */
export type K8sService = { 
/**
 * Service name
 */
name: string; 
/**
 * Namespace the service belongs to
 */
namespace: string; 
/**
 * Service type (e.g., "ClusterIP", "NodePort", "LoadBalancer", "ExternalName")
 */
type: string; 
/**
 * List of ports exposed by the service
 */
ports: K8sServicePort[]; 
/**
 * Number of endpoints (if available)
 */
endpoint_count: number | null }
/**
 * Kubernetes service port representation.
 */
export type K8sServicePort = { 
/**
 * Port name (if specified)
 */
name: string | null; 
/**
 * Port number
 */
port: number; 
/**
 * Target port (can be a number or string)
 */
target_port: string | null; 
/**
 * Protocol (e.g., "TCP", "UDP")
 */
protocol: string }
/**
 * Keycloak client representation.
 */
export type KeycloakClient = { 
/**
 * Client ID
 */
client_id: string; 
/**
 * Client name
 */
name: string; 
/**
 * Whether the client is enabled
 */
enabled: boolean }
/**
 * Keycloak realm representation.
 */
export type KeycloakRealm = { 
/**
 * Realm identifier
 */
realm: string; 
/**
 * Whether the realm is enabled
 */
enabled: boolean }
/**
 * Mapping between different system identifiers
 * Maps repository IDs to job IDs to namespaces, service names, etc.
 */
export type Mapping = { 
/**
 * Unique identifier for the mapping
 */
id: string; 
/**
 * GitLab repository ID (if applicable)
 */
repo_id: string | null; 
/**
 * Jenkins job ID (if applicable)
 */
job_id: string | null; 
/**
 * Kubernetes namespace
 */
namespace: string | null; 
/**
 * Service name in Kubernetes
 */
service_name: string | null; 
/**
 * Project ID this mapping belongs to
 */
project_id: string | null; 
/**
 * Environment ID this mapping belongs to
 */
environment_id: string | null }
/**
 * A project represents a software project that can have multiple environments.
 */
export type Project = { 
/**
 * Unique identifier for the project
 */
id: string; 
/**
 * Human-readable project name
 */
name: string; 
/**
 * Optional project description
 */
description: string | null; 
/**
 * List of environment IDs associated with this project
 */
environments: string[] }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * SonarQube metrics representation.
 */
export type SonarQubeMetrics = { 
/**
 * Code coverage percentage (0-100)
 */
coverage: number | null; 
/**
 * Number of bugs
 */
bugs: number; 
/**
 * Number of vulnerabilities
 */
vulnerabilities: number; 
/**
 * Number of code smells
 */
code_smells: number; 
/**
 * Technical debt in minutes (as string to avoid i64 BigInt issues)
 */
technical_debt: string | null }
/**
 * SonarQube project representation.
 */
export type SonarQubeProject = { 
/**
 * Project key (unique identifier)
 */
key: string; 
/**
 * Project name
 */
name: string; 
/**
 * Project qualifier (e.g., "TRK" for track, "APP" for application)
 */
qualifier: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
