use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{config, credentials, gitlab, jenkins, keycloak, kubernetes, notifications, preferences, quick_pane, recovery, sonarqube};

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        // Config management commands
        config::load_projects,
        config::save_projects,
        config::load_environments,
        config::save_environments,
        config::load_integrations,
        config::save_integrations,
        config::load_mappings,
        config::save_mappings,
        // Credentials management commands
        credentials::save_integration_credentials,
        credentials::get_integration_credentials,
        credentials::delete_integration_credentials,
        // GitLab integration commands
        gitlab::fetch_gitlab_projects,
        gitlab::fetch_gitlab_pipelines,
        gitlab::fetch_gitlab_webhooks,
        gitlab::trigger_gitlab_pipeline,
        // Jenkins integration commands
        jenkins::fetch_jenkins_jobs,
        jenkins::fetch_jenkins_builds,
        jenkins::fetch_jenkins_build_details,
        jenkins::trigger_jenkins_build,
        // Kubernetes integration commands
        kubernetes::fetch_k8s_namespaces,
        kubernetes::fetch_k8s_pods,
        kubernetes::fetch_k8s_services,
        kubernetes::fetch_k8s_pod_details,
        // SonarQube integration commands
        sonarqube::fetch_sonarqube_projects,
        sonarqube::fetch_sonarqube_metrics,
        // Keycloak integration commands
        keycloak::fetch_keycloak_realms,
        keycloak::fetch_keycloak_clients,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo run --bin export-bindings
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

// Note: The export_bindings test was removed because it causes
// STATUS_ENTRYPOINT_NOT_FOUND errors on Windows due to missing DLL dependencies.
// Use `cargo run --bin export-bindings` instead.
